In [1]:
import numpy as np
a=np.array([1,3,5,7,9,11])
print(a)

[ 1  3  5  7  9 11]


In [2]:
a=np.arange(0,12,2)
print(a)

[ 0  2  4  6  8 10]


In [3]:
a=np.linspace(5,8,13)
print(a)

[5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75 8.  ]


In [4]:
a=np.zeros((4,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
a=np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
arr=np.array([[-2,2,6,10],[14,18,22,-1]])
print(arr.shape)
arr.shape=(4,2)
print(arr)


(2, 4)
[[-2  2]
 [ 6 10]
 [14 18]
 [22 -1]]


In [15]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
a.reshape(3,2)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [16]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [20]:
a=np.arange(24)
print(a.ndim)

b=a.reshape(4,2,3)
print(b)

1
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]


In [21]:
x=[1,2,3]
a=np.asarray(x)
print(a)

[1 2 3]


In [22]:
x=(1,2,3)
a=np.asarray(x,dtype=float)
print(a)

[1. 2. 3.]


In [30]:
list=range(5)
it=iter(list)

x=np.fromiter(it,dtype=float)
print(x)

[0. 1. 2. 3. 4.]
